name: Build Site
run-name: Rebuilding the site 🚀
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run deployment script
        run: |
          chmod +x ./vue-ts/deploy.sh
          ./vue-ts/deploy.sh
          shell: bash